/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2022 - 2024 Thomas "stacksmashing" Roth - code@stacksmashing.net
 * Copyright (c) 2021 Raspberry Pi (Trading) Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 */

#ifndef PROBE_H_
#define PROBE_H_

#include <stdint.h>

// Commands accepted in tamarin_cmd_hdr.cmd.
enum TAMARIN_CMDS
{
    TAMARIN_INVALID = 0, // Invalid command
    TAMARIN_READ = 1,
    TAMARIN_WRITE = 2,
    TAMARIN_LINE_RESET = 3,
    TAMARIN_SET_FREQ = 4,
    TAMARIN_RESET = 5
};

// Status returned in tamarin_res_hdr.res.
//
// Values 0-7 are the raw three bit SWD acknowledge as it appeared on the wire, so
// the host always sees exactly what the target responded with. Only 1 (OK), 2
// (WAIT) and 4 (FAULT) are valid encodings; everything else means the target did
// not drive a well formed response. Values from 8 up are generated by the probe
// itself and never occur on the wire.
enum TAMARIN_STATUS
{
    // Raw SWD acknowledge values.
    TAMARIN_STATUS_OK = 1,
    TAMARIN_STATUS_WAIT = 2,    // returned once the probe has exhausted its retries
    TAMARIN_STATUS_FAULT = 4,
    TAMARIN_STATUS_NO_RESPONSE = 7, // line stayed high: target absent, unpowered or out of sync

    // Probe generated status values.
    TAMARIN_STATUS_PARITY_ERROR = 8,    // ACK was OK but the read data parity was wrong
    TAMARIN_STATUS_UNKNOWN_COMMAND = 9,
    TAMARIN_STATUS_BAD_ARGUMENT = 10,
};

void tamarin_probe_task(void);
void tamarin_probe_init(void);
void tamarin_probe_deinit(void);
void tamarin_probe_handle_write(uint8_t *data, unsigned total_bits);
void tamarin_probe_write_mode(void);
void tamarin_probe_read_mode(void);
uint32_t tamarin_probe_read_bits(unsigned bit_count);

#endif
