/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "faultier.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CaptureResponse, CaptureResponse, AUTO)


PB_BIND(CommandHello, CommandHello, AUTO)


PB_BIND(CommandCapture, CommandCapture, AUTO)


PB_BIND(CommandGlitch, CommandGlitch, AUTO)


PB_BIND(CommandSWDCheck, CommandSWDCheck, AUTO)


PB_BIND(CommandConfigureGlitcher, CommandConfigureGlitcher, AUTO)


PB_BIND(CommandConfigureADC, CommandConfigureADC, AUTO)


PB_BIND(CommandReadADC, CommandReadADC, AUTO)


PB_BIND(Command, Command, AUTO)


PB_BIND(ResponseOk, ResponseOk, AUTO)


PB_BIND(ResponseError, ResponseError, AUTO)


PB_BIND(ResponseHello, ResponseHello, AUTO)


PB_BIND(ResponseTriggerTimeout, ResponseTriggerTimeout, AUTO)


PB_BIND(ResponseADC, ResponseADC, AUTO)


PB_BIND(ResponseInfo, ResponseInfo, AUTO)


PB_BIND(ResponseSWDCheck, ResponseSWDCheck, AUTO)


PB_BIND(Response, Response, AUTO)


PB_BIND(CommandIOSetState, CommandIOSetState, AUTO)


PB_BIND(CommandIOGetState, CommandIOGetState, AUTO)


PB_BIND(ResponseIOGetState, ResponseIOGetState, AUTO)

























